In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv('../../../data/raw/up_groundwater_telemetry.csv')

In [3]:
df.head()

,SlNo,Station,Agency,State LGD Code,State,District LGD Code,District,Tehsil,Block,Village,...,Basin,Tributary,Subtributary,SubSubtributary,Local River,Latitude,Longitude,RL_MSL,Data Acquisition Time,Groundwater Level Telemetry 6 Hourly (meter)
0,1,390713- Jairampur PMS -Shallow,UPGW,9,Uttar Pradesh,187,VARANASI,-,-,-,...,-,-,-,-,-,25.41945,83.03,NaN,23-02-2024 18:00,-0.247
1,2,390713- Jairampur PMS -Shallow,UPGW,9,Uttar Pradesh,187,VARANASI,-,-,-,...,-,-,-,-,-,25.41945,83.03,NaN,24-02-2024 00:00,-0.256
2,3,390713- Jairampur PMS -Shallow,UPGW,9,Uttar Pradesh,187,VARANASI,-,-,-,...,-,-,-,-,-,25.41945,83.03,NaN,24-02-2024 06:00,-0.252
3,4,390713- Jairampur PMS -Shallow,UPGW,9,Uttar Pradesh,187,VARANASI,-,-,-,...,-,-,-,-,-,25.41945,83.03,NaN,24-02-2024 12:00,-0.167
4,5,390713- Jairampur PMS -Shallow,UPGW,9,Uttar Pradesh,187,VARANASI,-,-,-,...,-,-,-,-,-,25.41945,83.03,NaN,24-02-2024 18:00,-0.256

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7433230 entries, 0 to 7433229
Data columns (total 21 columns):
 #   Column                                        Dtype
---  ------                                        -----
 0   SlNo                                          int64
 1   Station                                       object
 2   Agency                                        object
 3   State LGD Code                                int64
 4   State                                         object
 5   District LGD Code                             int64
 6   District                                      object
 7   Tehsil                                        object
 8   Block                                         object
 9   Village                                       object
 10  River                                         object
 11  Basin                                         object
 12  Tributary                                     object
 13  Subtributary                                  object
 14  SubSubtributary                               object
 15  Local River                                   object
 16  Latitude                                      float64
 17  Longitude                                     float64
 18  RL_MSL                                        float64
 19  Data Acquisition Time                         object
 20  Groundwater Level Telemetry 6 Hourly (meter)  float64
dtypes: float64(4), int64(3), object(14)
memory usage: 1.2+ GB

In [5]:
df.shape

(7433230, 21)

In [6]:
df.describe()

,SlNo,State LGD Code,District LGD Code,Latitude,Longitude,RL_MSL,Groundwater Level Telemetry 6 Hourly (meter)
count,7.433230e+06,7433230.0,7.433230e+06,7.432965e+06,7.432965e+06,2.842581e+06,7.432591e+06
mean,3.716616e+06,9.0,1.779192e+02,2.698228e+01,8.014645e+01,1.763456e+02,-8.448293e+00
std,2.145789e+06,0.0,1.156439e+02,1.533195e+00,2.064870e+00,5.948046e+01,6.903338e+01
min,1.000000e+00,9.0,1.180000e+02,2.409871e+01,7.302982e+01,6.000000e+01,-2.333735e+04
25%,1.858308e+06,9.0,1.330000e+02,2.557000e+01,7.825574e+01,1.250000e+02,-1.413500e+01
50%,3.716616e+06,9.0,1.520000e+02,2.670464e+01,8.008416e+01,1.740000e+02,-6.671000e+00
75%,5.574923e+06,9.0,1.700000e+02,2.858966e+01,8.188250e+01,2.260000e+02,-2.057000e+00
max,7.433230e+06,9.0,6.610000e+02,3.013333e+01,8.432816e+01,4.000000e+02,1.010410e+03

In [7]:
df.columns

Index(['SlNo', 'Station', 'Agency', 'State LGD Code', 'State',
       'District LGD Code', 'District', 'Tehsil', 'Block', 'Village', 'River',
       'Basin', 'Tributary', 'Subtributary', 'SubSubtributary', 'Local River',
       'Latitude', 'Longitude', 'RL_MSL', 'Data Acquisition Time',
       'Groundwater Level Telemetry 6 Hourly (meter)'],
      dtype='object')

In [8]:
df.isnull().sum()

SlNo                                                  0
Station                                               0
Agency                                                0
State LGD Code                                        0
State                                                 0
District LGD Code                                     0
District                                              0
Tehsil                                                0
Block                                                 0
Village                                               0
River                                                 0
Basin                                                 0
Tributary                                             0
Subtributary                                          0
SubSubtributary                                       0
Local River                                           0
Latitude                                            265
Longitude                                           265
RL_MSL                                          4590649
Data Acquisition Time                                 0
Groundwater Level Telemetry 6 Hourly (meter)        639
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.dtypes

SlNo                                              int64
Station                                          object
Agency                                           object
State LGD Code                                    int64
State                                            object
District LGD Code                                 int64
District                                         object
Tehsil                                           object
Block                                            object
Village                                          object
River                                            object
Basin                                            object
Tributary                                        object
Subtributary                                     object
SubSubtributary                                  object
Local River                                      object
Latitude                                        float64
Longitude                                       float64
RL_MSL                                          float64
Data Acquisition Time                            object
Groundwater Level Telemetry 6 Hourly (meter)    float64
dtype: object

In [11]:
df.nunique()

SlNo                                            7433230
Station                                            2510
Agency                                                1
State LGD Code                                        1
State                                                 1
District LGD Code                                    75
District                                             79
Tehsil                                              140
Block                                                19
Village                                              24
River                                                 1
Basin                                                 1
Tributary                                             1
Subtributary                                          1
SubSubtributary                                       1
Local River                                           1
Latitude                                           2409
Longitude                                          2413
RL_MSL                                              240
Data Acquisition Time                            130524
Groundwater Level Telemetry 6 Hourly (meter)      94735
dtype: int64