In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv('../../../data/raw/punjab_groundwater_telemetry.csv')

In [3]:
df.head()

,SlNo,Station,Agency,State LGD Code,State,District LGD Code,District,Tehsil,Block,Village,...,Basin,Tributary,Subtributary,SubSubtributary,Local River,Latitude,Longitude,RL_MSL,Data Acquisition Time,Groundwater Level Telemetry Quadridaily (meter)
0,1,AMRITSAR;AJNALA;AJNALA;CHAK DOGRA;Vet. Hospital,Punjab GW,3,Punjab,27,AMRITSAR,AJNALA,AJNALA,Chak Dogra,...,-,-,-,-,-,31.885556,74.718611,NaN,20-03-2020 13:31,-8.675
1,2,AMRITSAR;AJNALA;AJNALA;CHAK DOGRA;Vet. Hospital,Punjab GW,3,Punjab,27,AMRITSAR,AJNALA,AJNALA,Chak Dogra,...,-,-,-,-,-,31.885556,74.718611,NaN,20-03-2020 13:32,-8.673
2,3,AMRITSAR;AJNALA;AJNALA;CHAK DOGRA;Vet. Hospital,Punjab GW,3,Punjab,27,AMRITSAR,AJNALA,AJNALA,Chak Dogra,...,-,-,-,-,-,31.885556,74.718611,NaN,20-03-2020 18:00,-8.557
3,4,AMRITSAR;AJNALA;AJNALA;CHAK DOGRA;Vet. Hospital,Punjab GW,3,Punjab,27,AMRITSAR,AJNALA,AJNALA,Chak Dogra,...,-,-,-,-,-,31.885556,74.718611,NaN,21-03-2020 06:00,-8.476
4,5,AMRITSAR;AJNALA;AJNALA;CHAK DOGRA;Vet. Hospital,Punjab GW,3,Punjab,27,AMRITSAR,AJNALA,AJNALA,Chak Dogra,...,-,-,-,-,-,31.885556,74.718611,NaN,21-03-2020 12:00,-8.000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 681295 entries, 0 to 681294
Data columns (total 21 columns):
 #   Column                                           Non-Null Count   Dtype
---  ------                                           --------------   -----
 0   SlNo                                             681295 non-null  int64
 1   Station                                          681295 non-null  object
 2   Agency                                           681295 non-null  object
 3   State LGD Code                                   681295 non-null  int64
 4   State                                            681295 non-null  object
 5   District LGD Code                                681295 non-null  int64
 6   District                                         681295 non-null  object
 7   Tehsil                                           254823 non-null  object
 8   Block                                            681295 non-null  object
 9   Village                                          681295 non-null  object
 10  River                                            681295 non-null  object
 11  Basin                                            681295 non-null  object
 12  Tributary                                        681295 non-null  object
 13  Subtributary                                     681295 non-null  object
 14  SubSubtributary                                  681295 non-null  object
 15  Local River                                      681295 non-null  object
 16  Latitude                                         681295 non-null  float64
 17  Longitude                                        681295 non-null  float64
 18  RL_MSL                                           0 non-null       float64
 19  Data Acquisition Time                            681295 non-null  object
 20  Groundwater Level Telemetry Quadridaily (meter)  681295 non-null  float64
dtypes: float64(4), int64(3), object(14)
memory usage: 109.2+ MB

In [5]:
df.shape

(681295, 21)

In [6]:
df.describe()

,SlNo,State LGD Code,District LGD Code,Latitude,Longitude,RL_MSL,Groundwater Level Telemetry Quadridaily (meter)
count,681295.00000,681295.0,681295.000000,681295.000000,681295.000000,0.0,681295.000000
mean,340648.00000,3.0,153.881882,30.742214,75.281447,NaN,-12.751678
std,196673.07016,0.0,239.490135,0.601389,0.740937,NaN,46.235618
min,1.00000,3.0,27.000000,29.729444,73.954700,NaN,-158.200000
25%,170324.50000,3.0,33.000000,30.313300,74.556000,NaN,-25.500000
50%,340648.00000,3.0,38.000000,30.568056,75.309722,NaN,-14.300000
75%,510971.50000,3.0,43.000000,31.160833,75.862500,NaN,-3.632000
max,681295.00000,3.0,662.000000,32.375278,79.765000,NaN,999.000000

In [7]:
df.columns

Index(['SlNo', 'Station', 'Agency', 'State LGD Code', 'State',
       'District LGD Code', 'District', 'Tehsil', 'Block', 'Village', 'River',
       'Basin', 'Tributary', 'Subtributary', 'SubSubtributary', 'Local River',
       'Latitude', 'Longitude', 'RL_MSL', 'Data Acquisition Time',
       'Groundwater Level Telemetry Quadridaily (meter)'],
      dtype='object')

In [8]:
df.isnull().sum()

SlNo                                                    0
Station                                                 0
Agency                                                  0
State LGD Code                                          0
State                                                   0
District LGD Code                                       0
District                                                0
Tehsil                                             426472
Block                                                   0
Village                                                 0
River                                                   0
Basin                                                   0
Tributary                                               0
Subtributary                                            0
SubSubtributary                                         0
Local River                                             0
Latitude                                                0
Longitude                                               0
RL_MSL                                             681295
Data Acquisition Time                                   0
Groundwater Level Telemetry Quadridaily (meter)         0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.dtypes

SlNo                                                 int64
Station                                             object
Agency                                              object
State LGD Code                                       int64
State                                               object
District LGD Code                                    int64
District                                            object
Tehsil                                              object
Block                                               object
Village                                             object
River                                               object
Basin                                               object
Tributary                                           object
Subtributary                                        object
SubSubtributary                                     object
Local River                                         object
Latitude                                           float64
Longitude                                          float64
RL_MSL                                             float64
Data Acquisition Time                               object
Groundwater Level Telemetry Quadridaily (meter)    float64
dtype: object

In [11]:
df.nunique()

SlNo                                               681295
Station                                               571
Agency                                                  1
State LGD Code                                          1
State                                                   1
District LGD Code                                      22
District                                               22
Tehsil                                                 41
Block                                                 158
Village                                               490
River                                                   1
Basin                                                   1
Tributary                                               1
Subtributary                                            1
SubSubtributary                                         1
Local River                                             1
Latitude                                              554
Longitude                                             552
RL_MSL                                                  0
Data Acquisition Time                               34725
Groundwater Level Telemetry Quadridaily (meter)     17617
dtype: int64